<a href="https://colab.research.google.com/github/yugan243/Deep-Learning-Pytorch/blob/main/2_pytorch_basics_playground.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Tensor Warmup


In [ ]:
import torch

In [ ]:
tensor_1 = torch.zeros(3,4)
tensor_2 = torch.ones(4,5)
tensor_3 = torch.rand(2,2)

print(tensor_1)
print(tensor_2)
print(tensor_3)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[0.6978, 0.6724],
        [0.7258, 0.1572]])


In [ ]:
tensor = torch.rand(2,3, dtype=torch.float64)
tensor

tensor([[0.9725, 0.5892, 0.9869],
        [0.6735, 0.1533, 0.8053]], dtype=torch.float64)

In [ ]:
t = torch.rand(4,4)
print(t.shape)
print(f"t: {t}")

y = t.view(-1,8)
print(y.shape)
print(f"y: {y}")

torch.Size([4, 4])
t: tensor([[0.4265, 0.7232, 0.1166, 0.8746],
        [0.1320, 0.7766, 0.5555, 0.0677],
        [0.2732, 0.0737, 0.3035, 0.5855],
        [0.7999, 0.0032, 0.1330, 0.7852]])
torch.Size([2, 8])
y: tensor([[0.4265, 0.7232, 0.1166, 0.8746, 0.1320, 0.7766, 0.5555, 0.0677],
        [0.2732, 0.0737, 0.3035, 0.5855, 0.7999, 0.0032, 0.1330, 0.7852]])


In [ ]:
x = torch.rand(4,4)
print(f"x: {x}")
print(x.dtype)

y = x.view(torch.int32)
print(f"y: {y}")
print(y.dtype)

x: tensor([[0.3357, 0.4708, 0.3011, 0.4096],
        [0.2782, 0.7651, 0.1847, 0.7373],
        [0.7551, 0.2607, 0.0940, 0.9464],
        [0.5574, 0.2081, 0.8270, 0.3600]])
torch.float32
y: tensor([[1051452834, 1055985562, 1050291874, 1053930080],
        [1049522074, 1061412839, 1044190612, 1060946138],
        [1061245066, 1048934422, 1036032304, 1064453164],
        [1057927233, 1045764748, 1062450097, 1052267720]], dtype=torch.int32)
torch.int32


In [ ]:
x = torch.tensor([
    [1,2,3],[4,5,6]
])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

This tensor is stored contiguosly in memory: 1, 2, 3, 4, 5, 6. Only the interpreting/visible order looks like this  
1 2  3
      
4 5  6


In [ ]:
x.view(6)

tensor([1, 2, 3, 4, 5, 6])

This works because the visible order and the memory order matches.


In [ ]:
y = x.t()
y

tensor([[1, 4],
        [2, 5],
        [3, 6]])

Pytorch usually does not moves the values in the memory. Memory is still 1, 2, 3, 4, 5, 6. But the logical order of the y is 1, 4, 2, 5, 3, 6.

In [ ]:
y.view(6)

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

This error throws because the existing physical memory order and the flatterned transpose order does not match. This is why reshape comes into play

Reshape will use view if possible. if not it would create a copy of the orginal data and rearrange it.

In [ ]:
y.reshape(6)

tensor([1, 4, 2, 5, 3, 6])

In [ ]:
t = torch.tensor([[1,2,3],[5,6,9]])
t

tensor([[1, 2, 3],
        [5, 6, 9]])

In [ ]:
print(t[0][2])
print(t[0,2])

tensor(3)
tensor(3)


In [ ]:
t[1][1]= 5
print(t)

tensor([[1, 2, 3],
        [5, 5, 9]])


In [ ]:
print(t[0:1])

tensor([[1, 2, 3]])


In [ ]:
print(t[:, 0:2])

tensor([[1, 2],
        [5, 5]])


In [ ]:
print(t[-1])

tensor([5, 5, 9])


In [ ]:
print(t[::1])

tensor([[1, 2, 3],
        [5, 5, 9]])


In [ ]:
if torch.cuda.is_available():
  device = torch.device("cuda")
else:
  device = torch.device("cpu")
t=t.to(device)
print(f"tensor t is in the device: {t.device}")

tensor t is in the device: cuda:0


In [ ]:
z = torch.rand(8, 100)


In [ ]:
z

tensor([[3.3094e-01, 6.8160e-02, 7.1014e-01, 1.8182e-01, 4.5848e-01, 2.7798e-01,
         1.7191e-01, 8.6756e-01, 7.6341e-01, 8.4964e-01, 4.3032e-01, 5.3155e-01,
         6.6948e-01, 9.3147e-01, 9.9835e-01, 9.9016e-01, 1.2968e-01, 1.1658e-01,
         6.9993e-01, 5.5699e-01, 9.5690e-01, 7.9597e-02, 3.5263e-01, 2.0328e-01,
         5.5582e-01, 8.0129e-01, 4.8622e-01, 2.0815e-01, 7.2668e-01, 8.8378e-01,
         3.2237e-01, 9.4567e-01, 4.2579e-01, 2.3275e-01, 5.7822e-01, 1.2713e-01,
         4.4273e-01, 3.7845e-01, 3.2520e-01, 4.6372e-01, 4.2804e-01, 6.1366e-01,
         4.6079e-01, 3.2087e-01, 2.0651e-02, 8.1408e-01, 1.8639e-01, 7.5894e-01,
         2.8488e-01, 4.4287e-01, 3.0166e-01, 1.7662e-01, 2.1084e-01, 5.3600e-01,
         1.2674e-01, 4.4077e-01, 5.9836e-01, 5.3901e-01, 4.9345e-01, 8.7418e-01,
         6.4465e-01, 1.5659e-01, 4.2408e-01, 7.1430e-02, 4.9531e-02, 6.8994e-01,
         3.5450e-02, 1.9657e-01, 8.0774e-01, 5.3872e-01, 8.4020e-01, 5.8473e-01,
         6.2458e-01, 2.7645e

In [ ]:
z = z.view(8, 5, 1, 1)
z

RuntimeError: shape '[8, 5, 1, 1]' is invalid for input of size 800

In [ ]:
z.shape

torch.Size([8, 100])

In [ ]:
z.size(0)

8