<a href="https://colab.research.google.com/github/yugan243/Deep-Learning-Pytorch/blob/main/4_pytorch_autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
from torchvision.models import resnet18, ResNet18_Weights

In [ ]:
model = resnet18(weights=ResNet18_Weights.DEFAULT)
data = torch.rand(1, 3, 64, 64)
labels = torch.rand(1, 1000)

In [ ]:
model

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
  

In [ ]:
prediction = model(data) #forward pass

Now we calculate the models error using it's prediction and the corresponding label. and we call the  **.backward()** on that error tensor. Autograd then calculates  and stores the gradients for each model parameter in the parameter's **.grad** attribute.

In [ ]:
loss = (prediction - labels).sum()
print(loss)
loss.backward() #backward pass

tensor(-507.1198, grad_fn=<SumBackward0>)


Now we load an optimizer, in this case it is SGD with a learning rate of 0.02 and momentum of 0.9. We register all the parameters of the model in the optimizer.

In [ ]:
optim = torch.optim.SGD(model.parameters(), lr=1e-2, momentum=0.9)


Finally, we call the **.step()** to initiate the gradient decent. The optimizer will then adjusts each parameters by its gradient stored in **.grad**.

In [ ]:
optim.step() #gradient decent

In [ ]:
import torch

x = torch.rand(3, requires_grad=True)
print(x)

y = x+2
print(y)

z = y*y*2
z = z.mean()
print(z)

z.backward() # dz/dx
print(x.grad)

tensor([0.6506, 0.8742, 0.7907], requires_grad=True)
tensor([2.6506, 2.8742, 2.7907], grad_fn=<AddBackward0>)
tensor(15.3833, grad_fn=<MeanBackward0>)
tensor([3.5341, 3.8323, 3.7210])
