<a href="https://colab.research.google.com/github/yugan243/Deep-Learning-Pytorch/blob/main/5_pytorch_autograd_playground.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
x = torch.tensor([
    [2.0, 2.0],
    [4.0, 8.0]
], requires_grad=True)

y = torch.tensor([
    [1.0, 1.0],
    [3.0, 2.0]
], requires_grad=True)

In [ ]:
print(x)
print(x.dtype)
print(y)
print(y.dtype)


tensor([[2., 2.],
        [4., 8.]], requires_grad=True)
torch.float32
tensor([[1., 1.],
        [3., 2.]], requires_grad=True)
torch.float32


In [ ]:
z = (3*x**2 + 5*y**2).sum()

In [ ]:
z.backward()

In [ ]:
print(x.grad)

tensor([[12., 12.],
        [24., 48.]])


In [ ]:
x = torch.tensor([[1, 2], [3, 4]], requires_grad=True, dtype=torch.float32)
x

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)

In [ ]:
for i in range(3):
  if x.grad != None:
    x.grad.zero_()
  y = (x**2).sum()
  y.backward()
  print(x.grad)

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


In [ ]:
x = torch.tensor([[1, 2], [3, 4]], requires_grad=True, dtype=torch.float32)

with torch.no_grad():
  y = x * 2
print(y.requires_grad)

False


Here pytorch doesn't build the computational graph.

In [ ]:
x = torch.tensor(5.0, requires_grad=True)
lr = 0.1

for step in range(10):
  y = (x - 3) ** 2
  y.backward()

  with torch.no_grad():
    x -= lr * x.grad
  x.grad.zero_()

  print(f"setp: {step}, x: {x.item()}, loss: {y.item()}")

setp: 0, x: 4.599999904632568, loss: 4.0
setp: 1, x: 4.279999732971191, loss: 2.559999704360962
setp: 2, x: 4.0239996910095215, loss: 1.638399362564087
setp: 3, x: 3.819199800491333, loss: 1.0485754013061523
setp: 4, x: 3.6553597450256348, loss: 0.6710883378982544
setp: 5, x: 3.524287700653076, loss: 0.4294964075088501
setp: 6, x: 3.4194302558898926, loss: 0.2748776078224182
setp: 7, x: 3.3355441093444824, loss: 0.1759217381477356
setp: 8, x: 3.26843523979187, loss: 0.11258985102176666
setp: 9, x: 3.2147481441497803, loss: 0.07205747812986374


Without **no_grad()**, PyTorch would try to remember:

`new x = old x - learning_rate × gradient`

as another operation in the computation graph.

But we do not want to later calculate derivatives through the update rule itself. We only want derivatives of the loss with respect to the current value of x.

So we want:



*   Loss calculation → tracked
*   Gradient calculation → tracked
*   Parameter update → not tracked



